redirects = [
  {from = "/help-center", to = "/training"},
  {from = "/docs", to = "https://shop.aeonlaser.us/a/docs/", force = true},
  {from = "/guides", to = "https://shop.aeonlaser.us/a/docs/", force = true},
  {from = "https://shop.aeonlaser.us/makecnc-terms", to = "https://shop.aeonlaser.us/pages/makecnc-terms", force = true},
  {from = "https://help.aeonlaser.us/", to = "https://shop.aeonlaser.us/a/docs/", force = true},
  {from = "https://aeonlaser.us/guides/lightburn-setup", to = "https://shop.aeonlaser.us/a/docs/category/lightburn", force = true},
  {from = "https://aeonlaser.us/guides/lightburn-camera-setup", to = "https://shop.aeonlaser.us/a/docs/accessories/lightburn-camera-setup", force = true},
  {from = "https://aeonlaser.us/guides/lightburn-camera-setup.html", to = "https://shop.aeonlaser.us/a/docs/accessories/lightburn-camera-setup", force = true},
  {from = "https://aeonlaser.us/guides/multi-roller", to = "https://shop.aeonlaser.us/a/docs/category/multi-roller", force = true},
  {from = "https://aeonlaser.us/guides/4-inch-lens-kit", to = "https://shop.aeonlaser.us/a/docs/accessories/4-inch-lens-kit-mira", force = true},
  {from = "https://aeonlaser.us/guides/removing-chiller", to = "https://shop.aeonlaser.us/a/docs/category/maintenance", force = true},
  {from = "https://aeonlaser.us/guides/smart-rotary", to = "https://shop.aeonlaser.us/a/docs/accessories/smart-rotary", force = true},
  {from = "https://aeonlaser.us/guides/getting-started", to = "https://shop.aeonlaser.us/a/docs/category/getting-started", force = true},
  {from = "https://aeonlaser.us/guides/rotary", to = "https://shop.aeonlaser.us/a/docs/category/accessories", force = true},
  {from = "https://aeonlaser.us/guides/unboxing", to = "https://shop.aeonlaser.us/a/docs/category/getting-started", force = true},
  {from = "https://aeonlaser.us/guides/remote", to = "/remote", force = true},
  {from = "/getting-started-mira-pro", to = "https://shop.aeonlaser.us/a/docs/category/getting-started", force = true},
  {from = "/getting-started-nova", to = "https://shop.aeonlaser.us/a/docs/category/getting-started", force = true},
  {from = "/customer-spotlight/home-bound-custom-decor", to = "/spotlight/home-bound-custom-decor", force = true},
  {from = "/customer-spotlight/beyond-laser-creations", to = "/spotlight/beyond-laser-creations", force = true},
  {from = "/customer-spotlight/designs-by-hope-yoder", to = "/spotlight/designs-by-hope-yoder", force = true},
  {from = "/customer-spotlight/that-mom-with-a-laser", to = "/spotlight/that-mom-with-a-laser", force = true},
  {from = "/customer-spotlight/lobo-designs", to = "/spotlight/lobo-designs", force = true},
  {from = "/customer-spotlight/pearl-and-pine", to = "/spotlight/pearl-and-pine", force = true},
  {from = "/emp-fiber", to = "/emp-galvo-setup", force = true},
  {from = "/emp-cabinet", to = "/emp-msc", force = true}
  ]
